import cadquery as cq

def create_corner_from_walls(front_wall: cq.Workplane, left_wall: cq.Workplane, 
                               front_translation: tuple = (0, 0, 0), 
                               left_translation: tuple = (0, 0, 0)) -> cq.Workplane:
    """
    Creates a corner by combining two pre-existing wall solids (front and left).
    
    The wall solids are assumed to be generated by lower-level assembly logic.
    Optional translations can be applied to each wall to ensure proper alignment
    at a 90° corner.
    
    :param front_wall: The pre-positioned front wall solid.
    :param left_wall: The pre-positioned left wall solid.
    :param front_translation: Translation to apply to the front wall as (x, y, z).
    :param left_translation: Translation to apply to the left wall as (x, y, z).
    :return: The combined corner as a CadQuery solid.
    """
    # Optionally adjust the position of the walls.
    adjusted_front = front_wall.translate(front_translation) if front_translation else front_wall
    adjusted_left = left_wall.translate(left_translation) if left_translation else left_wall
    
    # Union the two walls to form a corner.
    corner = adjusted_front.union(adjusted_left)
    return corner
