brick_length: 250
brick_width: 120
brick_height: 60

mortar_chamfer: 5  # Chamfer size for simulating mortar gaps

offset_x: 0
offset_y: 0
offset_z: 0

row_repetition: 4  # Number of rows per tile
tile_width: 4  # Number of bricks per row

bond_pattern: "flemish"  # Options: "flemish", "stretcher", "stack"

file_name: "stretcher_v1"  # 👈 Dynamically set file name here

export_formats:
  - step
  - stl
