import logging
import cadquery as cq
from ocp_vscode import show_object

# Global import/export utilities
from cad_pipeline.cad_engine.globals.import_handler import import_step_subassembly
from cad_pipeline.cad_engine.globals.export_handler import export_assembly
from cad_pipeline.models.assembly import Assembly

# Import the separate helper modules for transformation and assembly
from cad_pipeline.cad_engine.helpers.transform_wall import transform_wall
from cad_pipeline.cad_engine.helpers.assemble_walls import assemble_walls

logging.basicConfig(level=logging.DEBUG, format="%(levelname)s: %(message)s")

def generate_flemish_building():
    """
    Generates a 4-walled Flemish building by:
      1. Retrieving the 'flemish_building_generator' Assembly from the DB.
      2. Retrieving layout parameters from the assembly.
      3. Importing the cached child wall STEP file generated by the wall generator.
      4. Duplicating and transforming the child wall to form front, back, left, and right walls.
      5. Combining the walls (via union or as an assembly) to form the final building.
      6. Exporting and displaying the resulting building model.
    """
    logging.info("🚀 Starting Flemish Building Generation...")

    # 1. Retrieve the building assembly using the MPTT name.
    building_assembly = retrieve_assembly("flemish_building_generator")
    if not building_assembly:
        logging.error("❌ Building assembly not found.")
        return None

    # 2. Retrieve layout parameters from the assembly.
    layout = building_assembly.parameters.get("layout", {})
    front_wall_offset = layout.get("front_wall_offset", [0, 0, 0])
    back_wall_offset  = layout.get("back_wall_offset", [3000, 0, 0])
    left_wall_offset  = layout.get("left_wall_offset", [0, 0, 0])
    right_wall_offset = layout.get("right_wall_offset", [0, 2000, 0])
    rotate_walls = layout.get("rotate_walls", {"back": 180, "left": -90, "right": 90})
    assemble_mode = building_assembly.parameters.get("assemble_mode", "union")

    # 3. Import the cached child wall STEP file from the wall generator.
    child_wall_assembly = retrieve_assembly("flemish_wall_generator")
    if not child_wall_assembly:
        logging.error("❌ Child wall assembly not found.")
        return None

    child_wall_file = f"{child_wall_assembly.name}_child_wall.step"
    logging.info(f"🔄 Importing child wall from '{child_wall_file}'...")
    try:
        # Trigger wall regeneration if needed via generator_function (set to None if not used)
        child_wall = import_step_subassembly(child_wall_file, generator_function=None)
        if child_wall is None:
            logging.error(f"❌ Failed to import child wall from '{child_wall_file}'.")
            return None
    except Exception as e:
        logging.error(f"❌ Exception while importing child wall: {e}")
        return None

    # 4. Duplicate and transform the imported child wall for each side.
    front_wall = child_wall  # Front wall remains unchanged.
    back_wall = transform_wall(child_wall, rotate_walls.get("back", 180), back_wall_offset)
    left_wall = transform_wall(child_wall, rotate_walls.get("left", -90), left_wall_offset)
    right_wall = transform_wall(child_wall, rotate_walls.get("right", 90), right_wall_offset)

    # 5. Assemble the walls using the helper function.
    building_solid = assemble_walls(front_wall, back_wall, left_wall, right_wall, mode=assemble_mode)

    # 6. Export the final building model.
    export_flemish_building(building_solid, building_assembly)

    logging.info("🎨 Displaying Flemish Building in Viewer...")
    show_object(building_solid, name="Flemish Building")

    logging.info("✅ Flemish Building Generation Complete")
    return building_solid

def retrieve_assembly(name):
    """
    Retrieves an assembly by name from the database.
    
    :param name: Assembly name.
    :return: Assembly object or None if not found.
    """
    try:
        return Assembly.objects.get(name=name)
    except Assembly.DoesNotExist:
        logging.error(f"❌ ERROR: Assembly '{name}' not found in the database.")
        return None

def export_flemish_building(building_solid, building_assembly):
    """
    Exports the Flemish Building using the global export handler.
    
    :param building_solid: The final CadQuery solid or assembly representing the building.
    :param building_assembly: The assembly object from the database.
    """
    try:
        export_config = {
            "export_formats": ["step", "stl"],
            "component": building_assembly
        }
        exported_files = export_assembly(building_solid, **export_config)
        logging.info("✅ Building Export Completed!")
        for fmt, file_data in exported_files.items():
            logging.info(f"   - Exported Format: {fmt.upper()}, Size: {len(file_data.file_data)} bytes")
    except Exception as e:
        logging.error(f"❌ ERROR: Failed to export building: {e}")

if __name__ == "__main__":
    generate_flemish_building()
