name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "latest"
          driver: cloud

      - name: Build and push with caching
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/railworks:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/railworks:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/railworks:cache
          cache-to: type=inline,push=true
